### ISSUE TITLE
HTML中的Base64加密的图片显示不了，求解🙇

### ISSUE THREAD

**Issue by zhangylios** [pro648/BasicDemos-iOS#1]
您好，使用WKWebView的loadHTMLString方法加载html时，html文件中的图片显示不了(图片是Base64加密的)，困扰了许久，恳请赐教，非常感谢Thanks♪(･ω･)ﾉ

**Comment by pro648** [comment]
可以提供demo么？如果有demo，有利于进一步了解问题。

**Comment by zhangylios** [comment]
您好，这是demo，里面有html文件，就是这份html文件里面的图片无法显示。。非常感谢Thanks♪(･ω･)ﾉ
[WKWebView-master.zip](https://github.com/pro648/BasicDemos-iOS/files/3872467/WKWebView-master.zip)

**Comment by pro648** [comment]
在 html 中插入文件而不进行额外 HTTP 请求称为 data URL scheme。其格式为：

**Comment by pro648** [comment]
在 html 中插入文件而不进行额外 HTTP 请求称为 data URL scheme。其格式为：
```data:[<media type>][;base64],<data>```
例如，插入红点图片 ![Red-dot-5px](https://user-images.githubusercontent.com/20367411/69333634-05c96800-0c94-11ea-92ab-c32f97bd4a0c.png) 格式如下：
```
<img src="data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot”/>
```

[WKWebView-master.zip](https://github.com/pro648/BasicDemos-iOS/files/3874393/WKWebView-master.zip)

**Comment by zhangylios** [comment]
谢谢你，是这样没错，多谢
